part 4 try 1

diff --git a/.github/workflows/cicd-workflow.yaml b/.github/workflows/cicd-workflow.yaml
--- a/.github/workflows/cicd-workflow.yaml
+++ b/.github/workflows/cicd-workflow.yaml
@@ -49,3 +49,123 @@ jobs:
         with:
           name: 'cicd-demo-${{env.VERSION}}-all.jar'
           path: build/libs/*-all.jar
+
+      - name: 'Write Config & Key Files'
+        run: |
+          mkdir ~/.oci
+          echo "[DEFAULT]" >> ~/.oci/config
+          echo "user=${{secrets.OCI_USER_OCID}}" >> ~/.oci/config
+          echo "fingerprint=${{secrets.OCI_FINGERPRINT}}" >> ~/.oci/config
+          echo "region=${{secrets.OCI_REGION}}" >> ~/.oci/config
+          echo "tenancy=${{secrets.OCI_TENANCY_OCID}}" >> ~/.oci/config
+          echo "key_file=~/.oci/key.pem" >> ~/.oci/config
+          echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/key.pem
+          echo "${{secrets.VM_SSH_PUB_KEY}}" >> ~/.oci/id_vm.pub
+
+      - name: 'Install OCI CLI'
+        run: |
+          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
+          chmod +x install.sh
+          ./install.sh --accept-all-defaults
+          echo "::add-path::/home/runner/bin"
+          exec -l $SHELL
+
+      - name: 'Fix Config File Permissions'
+        run: |
+          oci setup repair-file-permissions --file /home/runner/.oci/config
+          oci setup repair-file-permissions --file /home/runner/.oci/key.pem
+
+      - name: 'Check Existing Instance'
+        run: |
+          echo "INSTANCE_OCID=$( \
+            oci compute instance list \
+            --lifecycle-state RUNNING \
+            --compartment-id ${{secrets.VM_COMPARTMENT_OCID}} \
+            --display-name cicd-demo \
+            --query "data [0].id" \
+            --raw-output \
+          )" >> $GITHUB_ENV
+
+      - name: 'Create Instance'
+        if: ${{!env.INSTANCE_OCID}}
+        run: |
+          echo "INSTANCE_OCID=$( \
+            oci compute instance launch \
+              --compartment-id ${{secrets.VM_COMPARTMENT_OCID}} \
+              --availability-domain ${{secrets.VM_AVAILABILITY_DOMAIN}} \
+              --shape ${{secrets.VM_SHAPE}} \
+              --assign-public-ip true \
+              --display-name cicd-demo \
+              --image-id ${{secrets.VM_CUSTOM_IMAGE_OCID}} \
+              --ssh-authorized-keys-file /home/runner/.oci/id_vm.pub \
+              --subnet-id ${{secrets.VM_SUBNET_OCID}} \
+              --wait-for-state RUNNING \
+              --query "data.id" \
+              --raw-output \
+          )" >> $GITHUB_ENV
+
+      - name: 'Get Instance IP'
+        run: |
+          echo "INSTANCE_IP=$( \
+            oci compute instance list-vnics \
+            --instance-id ${{env.INSTANCE_OCID}} \
+            --query 'data [0]."public-ip"' \
+            --raw-output \
+          )" >> $GITHUB_ENV
+
+      - name: 'Wait for SSH'
+        run: |
+          while ! nc -w5 -z ${{ env.INSTANCE_IP }} 22; do
+                  sleep 5
+                  echo "SSH not available..."
+          done; echo "SSH ready!"
+
+      - name: 'Install JDK 11'
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ env.INSTANCE_IP }}
+          username: opc
+          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
+          script: |
+            JDK_COUNT=$(yum list installed | grep 'java-11-openjdk' | wc -l)
+            if [ "$JDK_COUNT" == "0" ]; then
+              sudo yum install -y java-11-openjdk
+            else
+              echo "JDK 11 already installed"
+            fi
+            sudo mkdir -p /app
+
+      - name: 'Stop App'
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ env.INSTANCE_IP }}
+          username: opc
+          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
+          script: |
+            pid=$(ps aux | grep "[c]icd-demo.jar" | awk '{print $2}')
+            if [ "$pid" == "" ]; then
+              echo "Process not found"
+            else
+              kill -9 $pid
+            fi
+            sudo mkdir -p /app
+
+      - name: 'Push JAR'
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ env.INSTANCE_IP }}
+          username: opc
+          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
+          source: "build/libs/cicd-demo-${{env.VERSION}}-all.jar"
+          target: "app"
+          strip_components: 2
+
+      - name: 'Start App'
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ env.INSTANCE_IP }}
+          username: opc
+          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
+          script: |
+            sudo mv ~/app/cicd-demo-${{env.VERSION}}-all.jar /app/cicd-demo.jar
+            nohup java -jar /app/cicd-demo.jar > output.$(date --iso).log 2>&1 &
